### PR TITLE
Add ingest script for metatlas dataset

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
So this data set has 107486 molecules, after running the ingest we end up with only 46476 molecules in the database. As part of the ingestion code we uses the inchikey to check if we already have that molecule in the database. 

Looking at the raw data it looks like we have ~ 14982 molecules that have the same inchi.

Then looking at the server logs I am seeing the the following error from OpebBabel as we try to generate the inchikey:

```
*** Open Babel Warning  in CreateCisTrans
  Error in cis/trans stereochemistry specified for the double bond
```
So its having trouble creating the inchikey for a big portion of this dataset, hence they don't end up in the database ( or have the same inchikey? )

Tracing the code path from the generation of the inchikey it seems pretty torturous to me, here is the formats it seems to go through:

CJSON -- (Avogadro) --> SDF -- OpenBabel --> SMILES  -- OpenBabel --> XYZ -- OpenBabel --> inchikey

@cryos @muammar @psavery 
Apart from anything else this conversion path seems to drop any bonding information.

**Comment by cryos** [comment]
That looks like a bug - we shouldn't go from SMILES to XYZ to InChI. SMILES to InChI/InChI key is preferred. Not sure why it would go to XYZ - that should be avoided in general as it forces Open Babel to guess bonding which is present in CJSON, SDF and SMILES.

**Comment by cjh1** [comment]
If I remove the XYZ step from the convertion, OpenBabel gives me empty strings for the inchikeys. There is the following comment on the conversion, so I am guessing there was some issue?

```
# Hackish for now, convert to xyz first...
``

**Comment by cjh1** [comment]
I can confirm in the case we get the warning/error from openbabel an inchikey it return, it just must be a duplicate.

**Comment by cjh1** [comment]
[This](https://gist.github.com/cjh1/fd983af21721237f68856fb9772c629a) is a list of all the duplicate inchis in the raw dataset.

**Comment by cjh1** [comment]
Here are an of example of the SMILES and its associated inchikey for which we get the error/warning for: 

```
[CH3]=CCOC(=[CH3])O.COCC/C=[O]\[C]1(=[O][C@@H]2C(=[C]3=C(O[CH2]=C(O)O)CC(=[C](=C3[C@H]([C@@H]2C)O)O)NC(=O)/C(=C\CC[CH](=[C](=[OH])[C@@H]([CH](=[OH])[CH2][CH3])[CH3])[CH3])/[CH3])[C@H]1O)C => IGJIZKHSEUVLBN-UHFFFAOYSA-N
```

**Comment by cjh1** [comment]
I am also seeing the following exception:

```
girder_1          | Traceback (most recent call last):
girder_1          |   File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
girder_1          |     callback(self)
girder_1          |   File "/mongochemserver/girder/molecules/molecules/utilities/async_requests.py", line 64, in _finish_svg_gen
girder_1          |     raise ValidationException('Invalid inchikey (%s)' % inchikey)
girder_1          | girder.exceptions.ValidationException: Invalid inchikey (AWUHMVUVLZGRBZ-HHHXNRCGSA-N)
```

**Comment by psavery** [comment]
> I am also seeing the following exception:
> 
> ```
> girder_1          | Traceback (most recent call last):
> girder_1          |   File "/usr/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
> girder_1          |     callback(self)
> girder_1          |   File "/mongochemserver/girder/molecules/molecules/utilities/async_requests.py", line 64, in _finish_svg_gen
> girder_1          |     raise ValidationException('Invalid inchikey (%s)' % inchikey)
> girder_1          | girder.exceptions.ValidationException: Invalid inchikey (AWUHMVUVLZGRBZ-HHHXNRCGSA-N)
> ```

@cjh1 That is strange.The SVG generation is done asynchronously. It saves a copy of the inchikey [here](https://github.com/OpenChemistry/mongochemserver/blob/8c99caea6ea03a26f124ed87d76d044047e6b0d9/girder/molecules/molecules/utilities/async_requests.py#L37) so it can find the molecule when it finishes to update it. That exception means the query couldn't find a molecule with that inchikey...

**Comment by cjh1** [comment]
With the changes to our conversion code. I am now able to import 97884 structures.

**Comment by psavery** [comment]
This is working very nicely for the most part!

However, I get an exception after every chunk size (default == 1000) completes, and then I have to restart it if I want to keep going. Here is my exception (which causes other exceptions):

```
Traceback (most recent call last):
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 552, in write_bytes
    await self.body.write(writer)
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.7/site-packages/aiohttp/payload.py", line 231, in write
    await writer.write(self._value)
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.7/site-packages/aiohttp/http_writer.py", line 101, in write
    self._write(chunk)
  File "/home/patrick/virtualenvs/mongochemdeploy/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
```

**Comment by cjh1** [comment]
@psavery Did you say you where only seeing this issue on one machine?

**Comment by psavery** [comment]
@cjh1 No, it worked the first time I ran it on a different machine. But then I started running into the same problem again. I'm not sure what causes it, but it seems to happen more often than not for me.

**Comment by cjh1** [comment]
@psavery Can you test this out again and see if you can recreate the problem you were seeing?

**Comment by psavery** [comment]
I have still ran into the issue I was seeing earlier (on multiple computers as well). However, I was able to fix it by using a new `ClientSession` for each http request, similar to what was done to fix a problem [here](https://stackoverflow.com/a/54711974).

This is not that desirable, as I think a `ClientSession` should be present for the duration of the program. However, it fixes the issue I was experiencing. I was able to go through the full ingest, and I got 98596 molecules in my database.

**Review by psavery — APPROVED** [review]
LGTM

**Comment by cjh1** [comment]
@psavery Thanks for testing this and getting to the bottom of the issue!

**Pull request merged**
