### PR TITLE
Added script to upload molecules from qcarchive

### PR DESCRIPTION
**Pull request by psavery**
The script contains a few variables at the beginning that
define the qcarchive collection from which to obtain the
molecules. The default is the "JGI Metabolite Set 1"
OptimizationDataset.

The qcarchive molecule id is stored in the "provenance", so
that a user can refer back to the molecule in the qcarchive
if they want more information.

For some bigger molecules, it takes a very long time (>1 minute) to
upload, and the mongochemclient will be unable to communicate
with the girder server during this time. We should probably figure
out why some of them take so long.

Depends on [this PR](https://github.com/OpenChemistry/mongochemserver/pull/142).

### CODE REVIEW

**Comment by psavery** [comment]
@cjh1 Should I add a `requirements.txt` file or `setup.py` to automatically download the required dependencies to run this?

**Comment by cjh1** [comment]
`requirements.txt` should be fine for now.

**Comment by psavery** [comment]
It is added!

**Comment by cjh1** [comment]
This is looking good and we can merge as is. I have push my script as well [here](https://github.com/OpenChemistry/mongochemdeploy/pull/83). What I think we should do is merge them into a single ingest CLI ( once they are both merged to master). So we should be able to something like:

```
ocingest qcacrhive ...
ocingest metalas ...
```

I think this can be achieved using click and click-plugins. This should allow use to plugin sub commands for other data sources.

**Comment by psavery** [comment]
By the way, I figured out that the reason it takes a long time for big molecules is almost entirely due to SVG generation. It looks like generating an SVG is very slow for big molecules in Open Babel. There might be a way we can speed it up, though - I am not sure. But we might also consider making svg generation an asynchronous job.

**Comment by cjh1** [comment]
@psavery Yes, I am also seeing the SVG generation take along time with my ingest. An asynchronous approach would be a good idea.

**Comment by psavery** [comment]
@cjh1 I thought it might have been caused by us passing in a line format (SMILES) for the SVG generation, and I thought maybe a 3D format would be faster. Unfortunately, it does not look like it is faster according to my tests.

**Comment by cryos** [comment]
SVGs are 2D, so 3D data won't help and they will run a layout algorithm based on connectivity. That is why I just wanted to use line formats - it is the fastest way to an SVG.

**Comment by cryos** [comment]
This looks ready to merge, and the other PR has been merged.

**Pull request merged**
