### PR TITLE
Update jupyterhub and have it wait for the db

### PR DESCRIPTION
**Pull request by psavery**
This updates jupyterhub to the latest release and has it wait for the
jupyterhub-db to become available before starting.

I think the current setup might not work, and needs more testing.

Fixes: #109 
Fixes: #110

### CODE REVIEW

**Comment by psavery** [comment]
The current state: the jupyterhub image now does wait for jupyterhub-db to become available, but the notebooks are not working for some reason.

**Comment by alesgenova** [comment]
@psavery @cjh1 

I tried to open a PR on this branch, and it opened it on your fork.

https://github.com/psavery/mongochemdeploy/pull/1

Tagging you here just in case you missed it

**Comment by psavery** [comment]
@alesgenova Okay, I approved it.

**Comment by cjh1** [comment]
@psavery What do we need todo to get this out of draft?

**Comment by psavery** [comment]
@cjh1 I haven't tried it since Alessandro's changes were merged. I'll give it a try. If it works fine, then I think it's ready.

**Comment by psavery** [comment]
Just rebased on master

**Comment by psavery** [comment]
@cjh1 @alesgenova So I think I remember that we need to update some docker images past 1.0 for this to work. However, even when I do so, I get an error with jupyterhub (pasted below). I think I remember @alesgenova mentioning that we need to update something with jupyterhub as well?

```python
jupyterhub        | [D 2021-02-15 16:22:48.655 JupyterHub application:730] Looking for /srv/jupyterhub/jupyterhub_config in /srv/jupyterhub
jupyterhub        | [E 2021-02-15 16:22:48.656 JupyterHub app:2859]
jupyterhub        |     Traceback (most recent call last):
jupyterhub        |       File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2856, in launch_instance_async
jupyterhub        |         await self.initialize(argv)
jupyterhub        |       File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2347, in initialize
jupyterhub        |         self.load_config_file(self.config_file)
jupyterhub        |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 87, in inner
jupyterhub        |         return method(app, *args, **kwargs)
jupyterhub        |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 775, in load_config_file
jupyterhub        |         for (config, filename) in self._load_config_files(filename, path=path, log=self.log,
jupyterhub        |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 737, in _load_config_files
jupyterhub        |         config = loader.load_config()
jupyterhub        |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/loader.py", line 616, in load_config
jupyterhub        |         self._read_file_as_dict()
jupyterhub        |       File "/usr/local/lib/python3.8/dist-packages/traitlets/config/loader.py", line 648, in _read_file_as_dict
jupyterhub        |         exec(compile(f.read(), conf_filename, 'exec'), namespace, namespace)
jupyterhub        |       File "/srv/jupyterhub/jupyterhub_config.py", line 46, in <module>
jupyterhub        |         spawn_cmd += ' --NotebookApp.allow_origin=%s' % os.environ['ORIGIN']
jupyterhub        |       File "/usr/lib/python3.8/os.py", line 675, in __getitem__
jupyterhub        |         raise KeyError(key) from None
jupyterhub        |     KeyError: 'ORIGIN'
jupyterhub        |     
jupyterhub        | [D 2021-02-15 16:22:48.657 JupyterHub application:834] Exiting application: jupyterhub
jupyterhub exited with code 1
```

**Comment by cjh1** [comment]
@psavery What was the reason for move `Dockerfile.jupyterlab` and `Dockerfile.jupyterhub`?

**Comment by psavery** [comment]
@cjh1 I think it was just to easier keep track of which files are associated with which Dockerfile.

**Comment by cjh1** [comment]
> @cjh1 I think it was just to easier keep track of which files are associated with which Dockerfile.
Fair enough

**Comment by cjh1** [comment]
@psavery @alesgenova Can you review my changes, then we will get this one in.

**Review by alesgenova — APPROVED** [review]
LGTM!

**Review by psavery — COMMENTED** [review]
LGTM. I guess I can't approve my own PR!

**Comment by cjh1** [comment]
Thanks @alesgenova and @psavery, merging

**Pull request merged**
