### PR TITLE
ORCA docker image

### PR DESCRIPTION
**Pull request by muammar**
In this PR I am adding an orca image. To create this image the following steps have to be followed:

1. Download an ORCA tarball from https://orcaforum.kofo.mpg.de/app.php/dlext/
2. Copy the tarball to /path/to/git/openchemistry/mongochemdeploy/docker/orca
3. Build the image using the command below:

```
docker build -t openchemistry/orca . --build-arg tarball=orca_4_1_2_linux_x86-64_openmpi313.tar.xz
```

I tested that it is working but there might still be work to be done to get it ready to merge into `master`.

### CODE REVIEW

**Comment by cjh1** [comment]
@muammar This is looking good, thank you! What do you think is still left todo? I will test it out when I have the bandwidth to download the 3gb :smile:

**Comment by muammar** [comment]
> @muammar This is looking good, thank you! What do you think is still left todo?

I have to find a way of including these to the `ChemicalJSon` file:

1. Total energy. 
2. Molecular orbital information to plot them. 
3. IR data. 
4. Test the minimum number of binaries needed. The tarball is 3GB in size but when you unpack it the docker image becomes ~20GB:

```
muammar@jedi ~ 
  % docker images                                                        !10010
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
openchemistry/orca   latest              5b5f3add52d1        19 hours ago        20.7GB
```

> I will test it out when I have the bandwidth to download the 3gb  Could you give an example calculation to test it with?

LOL. Unpacked, the tarball is ~16GB...

**Comment by cjh1** [comment]
@muammar I tried to download the tarball, but I don't see it at that link, do I need to login?

**Comment by muammar** [comment]
> @muammar I tried to download the tarball, but I don't see it at that link, do I need to login?

This would be the download link https://orcaforum.kofo.mpg.de/app.php/dlext/ and unfortunately one has to register in the forum to have access to it. :S

**Comment by alesgenova** [comment]
@muammar , here is some explanation for how to save things in `cjson`

> I have to find a way of including these to the `ChemicalJSon` file:
> 
>     1. Total energy.
We need to formalize better how we store the computed properties, but for now I've been putting the total energy of a calculation under `cjson['properties']['totalEnergy']` as `J / mol` (NOT `kJ`)
> 
>     2. Molecular orbital information to plot them.
This is a little harder, cause we need to save both the basis set information (gaussian basis only), as well as the molecular orbital coefficients. I pretty much did the conversion manually when I wrote the `PSI4` image, you can get some inspiration from here https://github.com/OpenChemistry/openchemistrypy/blob/master/openchemistry/io/utils.py
> 
>     3. IR data.
> 
Vibrations go in `cjson['vibrations']`. The value is a object like this:
```
{
  'frequencies': N-dimensional array of the frequencies in cm-1,
  'intensities': N-dimensional array of the IR intensities,
  'modes': N-dimensional array just for indexing (i.e. [0, 1, 2, ...]),
  'eigenVectors': N-dimensional array of the atomic displacements for each normal mode
}
```
`eigenVectors` has shape `(N, 3 * nAtoms)`, and should look like this:
```
[
  [a0_dx0, a0_dy0,  a0_dz0, a1_dx0, a1_dy0,  a1_dz0, ...],
  [a0_dx1, a0_dy1,  a0_dz1, a1_dx1, a1_dy1,  a1_dz1, ...],
  ...
]
```

**Comment by muammar** [comment]
@alesgenova Thanks for your message, it was really helpful!. 

> @muammar , here is some explanation for how to save things in `cjson`
> 
> > I have to find a way of including these to the `ChemicalJSon` file:
> > ```
> > 1. Total energy.
> > ```
> 
> We need to formalize better how we store the computed properties, but for now I've been putting the total energy of a calculation under `cjson['properties']['totalEnergy']` as `J / mol` (NOT `kJ`)
> 

This is done now. 

> > ```
> > 2. Molecular orbital information to plot them.
> > ```
> 
> This is a little harder, cause we need to save both the basis set information (gaussian basis only), as well as the molecular orbital coefficients. I pretty much did the conversion manually when I wrote the `PSI4` image, you can get some inspiration from here https://github.com/OpenChemistry/openchemistrypy/blob/master/openchemistry/io/utils.py
> 
> > ```
> > 3. IR data.
> > ```
> 
> Vibrations go in `cjson['vibrations']`. The value is a object like this:
> 
> ```
> {
>   'frequencies': N-dimensional array of the frequencies in cm-1,
>   'intensities': N-dimensional array of the IR intensities,
>   'modes': N-dimensional array just for indexing (i.e. [0, 1, 2, ...]),
>   'eigenVectors': N-dimensional array of the atomic displacements for each normal mode
> }
> ```
> 
> `eigenVectors` has shape `(N, 3 * nAtoms)`, and should look like this:
> 
> ```
> [
>   [a0_dx0, a0_dy0,  a0_dz0, a1_dx0, a1_dy0,  a1_dz0, ...],
>   [a0_dx1, a0_dy1,  a0_dz1, a1_dx1, a1_dy1,  a1_dz1, ...],
>   ...
> ]
> ```

I followed the `Psi4` container code and think everything should be working now. There is still a problem with the IR parsing that has to be fixed in `cclib`. 

Just one last thing I wanted to ask. Should everything from [line 89](https://github.com/OpenChemistry/mongochemdeploy/pull/72/files#diff-da8dc981e668e32a0095acc28881ee4bR89) be included added as a module under [`openchemistry.io`](https://github.com/OpenChemistry/openchemistrypy/tree/master/openchemistry/io)?

**Comment by cjh1** [comment]
> Just one last thing I wanted to ask. Should everything from [line 89](https://github.com/OpenChemistry/mongochemdeploy/pull/72/files#diff-da8dc981e668e32a0095acc28881ee4bR89) be included added as a module under [`openchemistry.io`](https://github.com/OpenChemistry/openchemistrypy/tree/master/openchemistry/io)?
@muammar Yes, I think this would be a good addition as a reader to `openchemistry.io`

**Comment by cjh1** [comment]
@muammar Is this one ready to go?

**Comment by muammar** [comment]
> @muammar Is this one ready to go?

Hi @cjh1. Yes, this is ready to go!!1

**Review by cjh1 — APPROVED** [review]

**Comment by cjh1** [comment]
@muammar Sorry for the delay!

**Pull request merged**
